id: I2145FE54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:01:21+00:00'
last_modified: '2022-06-07T15:01:19.153615+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22325
  title: གཏོར་མ་བརྒྱ་རྩ་ཤིན་ཏུ་བསྡུས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2558':
      image_group_id: I1PD36253
      title: ''
      total_pages: 14
      order: 1
      base_file: 2558.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
