id: P001758
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:19:38.545019
source_metadata:
  id: bdr:W22325
  title: གཏོར་མ་བརྒྱ་རྩ་ཤིན་ཏུ་བསྡུས་པ
  author: ''
  volumes:
    b8e9854c558a45798c240a0918fd772b:
      image_group_id: I1PD36253
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
